name: Vax Update 

on:
  # push:
  #   branches:
  #     - master
  schedule:
     # Half past every hour from 04:30 UTC to 11:30 UTC (14:30 - 21:30 AEST) each day
    - cron: '30 4-11 * * *'

defaults:
  run:
    shell: bash


jobs:
  vaxupdate:
    name: Vax Update
    runs-on: ubuntu-latest
    env:
      MPLBACKEND: Agg
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install numpy scipy matplotlib pandas requests

      - name: Run
        run: |
          if python check-vax-outdated.py | grep "outdated!"; then
            python aus_vax.py
            python aus_vax.py project
          fi

      - name: Git pull
        run: git pull --rebase --autostash

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Vax update
